openapi: 3.0.0
info:
  title: Bank Service API
  description: Banking API for managing customers and transfers.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /v1/customers:
    post:
      summary: Create a new customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDTO'
      responses:
        201:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDTO'
        204:
          description: No content

    get:
      summary: Lists all customers
      responses:
        200:
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerDTO'

  /v1/customers/{accountNumber}:
    get:
      summary: Returns a customer by account number
      parameters:
        - name: accountNumber
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDTO'
        400:
          description: Not found

  /v1/customers/transfer:
    post:
      summary: Performs a transfer between accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferDTO'
      responses:
        200:
          description: Sucess

  /v1/customers/transfers/{accountNumber}:
    get:
      summary: Lists all transfers of a customer
      parameters:
        - name: accountNumber
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Transfer list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransferDTO'

components:
  schemas:
    CustomerDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        accountNumber:
          type: integer
        balance:
          type: number
          format: double
        transfers:
          type: array
          items:
            $ref: '#/components/schemas/TransferDTO'

    TransferDTO:
      type: object
      properties:
        sourceAccount:
          type: integer
        destinationAccount:
          type: integer
        ammount:
          type: number
          format: double
        transferDate:
          type: string
          format: date-time
        status:
          type: string
